import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { journalData } from '../src/data/journals.ts';
import {
  doiSlug,
  extFromContentType,
  fallbackCoverSvg,
  isPlaceholderCover,
  normalizeDoi,
  resolveCoverSource,
} from '../server/src/journalCoverResolve.ts';

const outDir = path.resolve('public/images/journals');
const mapPath = path.resolve('src/data/journalCovers.ts');

const covers: Record<string, string> = {};

await mkdir(outDir, { recursive: true });

for (const journal of journalData) {
  const doi = normalizeDoi(journal.doi);
  if (!doi) continue;
  if (!isPlaceholderCover(journal.image) && journal.image.includes('/images/journals/') && !journal.image.includes('default.svg')) {
    continue;
  }

  process.stdout.write(`${doi} ... `);
  const source = await resolveCoverSource(doi);
  const slug = doiSlug(doi);
  if (source) {
    const ext = extFromContentType(source.contentType, source.url);
    const fileName = `${slug}${ext}`;
    await writeFile(path.join(outDir, fileName), source.buffer);
    covers[doi] = `/images/journals/${fileName}`;
    console.log(`saved ${fileName} (${source.buffer.length}B)`);
  } else {
    const fileName = `${slug}.svg`;
    await writeFile(path.join(outDir, fileName), fallbackCoverSvg(journal.journal, journal.date));
    covers[doi] = `/images/journals/${fileName}`;
    console.log(`fallback svg`);
  }
}

const body = Object.entries(covers)
  .map(([doi, image]) => `  ${JSON.stringify(doi)}: ${JSON.stringify(image)},`)
  .join('\n');

await writeFile(
  mapPath,
  `// Generated by scripts/fetch-journal-covers.ts — paper cover paths keyed by DOI.\nexport const journalCovers: Record<string, string> = {\n${body}\n};\n`
);

console.log(`Wrote ${Object.keys(covers).length} covers to ${mapPath}`);
